const express = require('express')
const route = express.Router()
const AdminDAO = require('../controllers/AdminDAO')
const BookDAO = require('../controllers/BookDAO')
const Admin = require('../models/Admin')

route.get('/trash-book/:id/restore/:slug',AdminDAO.restoreBook)
route.get('/trash-book/:id',AdminDAO.getTrashBook)
route.get('/delete-book/:id/:slug',AdminDAO.deleteBook)
route.get('/manage-book/:id',AdminDAO.getListBook)
route.get('/manage-user/:id',AdminDAO.getListUser)
route.post('/:id/updateAvatar',AdminDAO.upload.single('avatar'),AdminDAO.updateAvatar)
route.get('/:id/loadAvatar',AdminDAO.loadAvatar)
route.post('/infor/:id',AdminDAO.updateInfor)
route.get('/infor/:id',AdminDAO.getInfor)
route.get('/manage/:id/:slug',BookDAO.indexWaitingBook)
route.get('/:id',AdminDAO.index)
module.exports = route